# Generated by Django 5.0.1 on 2024-01-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('family', models.TextField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
