# Generated by Django 5.0.1 on 2024-01-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_watering_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='soil',
            field=models.ManyToManyField(to='main_app.soil'),
        ),
    ]
