# Generated by Django 5.0.1 on 2024-01-12 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_soil_plant_soil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='soil',
            new_name='soils',
        ),
    ]
